library(rCharts)
library(shiny)

require(markdown)

shinyUI(fluidPage(

    # Application title
    h1("Baby names over the years", align="center"),
    h4("Top 20 most-used baby names from 1960-2013", align="center"),

    includeMarkdown("intro.md"),

    # First graph + controls
    fluidRow(
        column(3,
               includeMarkdown("name_count_instructions.md")),

        column(3,
            # Gender to explore
            radioButtons("gender_choice", label = h3("Gender"),
                         choices = list("Male" = "M", "Female" = "F"),
                         selected = "M"),

            # Select names to plot - dynamically generated by server
            uiOutput("name_select_ui")
        ),

        column(6,
               showOutput("name_plot", "highcharts")
               )
    ),

    # Second graph + controls and description
    includeMarkdown("ranking_description.md"),

    fluidRow(
        column(3,
               includeMarkdown("name_rank_instructions.md")
        ),

        column(3,
               # Gender to show ranks for
               radioButtons("gender_rank_choice", label = h3("Gender"),
                            choices = list("Male" = "M", "Female" = "F"),
                            selected = "F"),

                # Select year range to plot
                sliderInput("year_select", "Year Range:",
                            min = 1960, max = 2013, value = c(1980, 2000), sep="", step=1)
        ),

        column(6,
               showOutput("rank_plot", "highcharts")
        )
    ),

    # Summary and end-notes
    includeMarkdown("summary.md"),

    dataTableOutput('names_table')
))

#         # Select year range to plot
#         sliderInput("years", "Year Range:",
#                     min = 1960, max = 2013, value = c(1980, 2000), sep="", step=1)

#         column(7,
#             dataTableOutput('names_table')
#             )
